subject: CS
number: 125
semesters:
  Fall2018:
    name: Fall 2018
    start: "08-27-2018"
    end: "12-12-2018"
    staffCourse:
      number: 199
      section: 125
    sheets:
      staff: '1uWF4QZ3GNIKosJ9LolB8OPF3ybsB04bCpEsFDuQSvAs'
      CAs: '1t41oad983tCsBDxb_K6YWyEBQ7AZrdSmziLN-HJRclc'
      staffInfo: '1dd34sJ2vGWdxz1U6h30vMowc95eNIhW3yhdOrQhfa04'
      labs: '1vbwL5-uEySqJuGHwK3-Q--J3jh4GFEjuVjJk3jcWDPQ'
      officeHours: '1FMZWzTQb--ydRtICZYoc-v5iAwcXLqLyegWsStbuVL0'
    courses: 'https://courses.illinois.edu/search/schedule/2018/fall/CS/125?sess='
    instructors:
      - name: Geoffrey Challen
        email: challen@illinois.edu
    manualSectionAssignments:
      liiamb2@illinois.edu: [ 'EMP' ]
    extraSections:
      EMP:
        CRN: 55186
        type: Lecture
        name: EMP
        days: R
        times:
          start: 05:00PM
          end: 06:50PM
        location: 2310 Everitt Elec & Comp Engr Lab
  Spring2018:
    start: "01-16-2018"
    end: "05-11-2018"
    staffSheet: '1UkEOdYgHRPxlP8uDrQVJRlgbTSRzcWdiPOB5rvtX3mc'
    officehours: '1NA-BHWlPy18dnzTFcmA0qu1Wzoa_CiTn2y8AuBW2zpM'
    courses: 'https://courses.illinois.edu/search/schedule/2018/spring/CS/125?sess='
    instructors:
      - name: Geoffrey Challen
        email: challen@illinois.edu
    extraSections:
      EMP:
        CRN: 63080
        type: Lecture
        name: EMP
        days: M
        times:
          start: 05:00PM
          end: 06:50PM
        location: 1404 Siebel Center for Comp Sci
        active: true
people:
  startLoggingDaysBefore: 60
  endLoggingDaysAfter: 30
  CAActiveGracePeriodDays: 14
  officeHourGracePeriodDays: 14
databaseName: cs125
mailServer: 192.17.96.8
discourseURL: https://cs125-forum.cs.illinois.edu
thumbnail: 200.0
labPrefix: AY
lecturePrefix: AL
semesterStartsDaysBefore: 14
semesterEndsDaysAfter: 14
timezone: "America/Chicago"
