course: CS-125-Spring_2018
database: Spring2018
addTo: AL1
server: 192.17.96.8
discourse: https://cs125-forum.cs.illinois.edu
sheet: '1UkEOdYgHRPxlP8uDrQVJRlgbTSRzcWdiPOB5rvtX3mc'
officehours: '1NA-BHWlPy18dnzTFcmA0qu1Wzoa_CiTn2y8AuBW2zpM'
courses: 'https://courses.illinois.edu/search/schedule/2018/spring/CS/125?sess='
sectionInfo:
  EMP:
    CRN: 63080
    type: Lecture
    name: EMP
    days: M
    times:
      start: 05:00PM
      end: 06:50PM
    location: 1404 Siebel Center for Comp Sci
