semesters:
  Spring2018:
    start: "01-16-2018"
    end: "05-11-2018"
    course: CS-125-Spring_2018
    sheet: '1UkEOdYgHRPxlP8uDrQVJRlgbTSRzcWdiPOB5rvtX3mc'
    officehours: '1NA-BHWlPy18dnzTFcmA0qu1Wzoa_CiTn2y8AuBW2zpM'
    courses: 'https://courses.illinois.edu/search/schedule/2018/spring/CS/125?sess='
    extraSections:
      EMP:
        CRN: 63080
        type: Lecture
        name: EMP
        days: M
        times:
          start: 05:00PM
          end: 06:50PM
          location: 1404 Siebel Center for Comp Sci
          active: true
  Fall2018:
    start: "08-27-2018"
    end: "12-20-2018"
    course: CS-125-Fall_2018
    courses: 'https://courses.illinois.edu/search/schedule/2018/fall/CS/125?sess='
people:
  startLoggingDaysBefore: 60
  endLoggingDaysAfter: 30
database: cs125
server: 192.17.96.8
discourse: https://cs125-forum.cs.illinois.edu
thumbnail: 200.0
labPrefix: AY
semesterStartsDaysBefore: 14
semesterEndsDaysAfter: 14
timezone: "America/Chicago"
