version: "2"
networks:
  peoplelogger:
    driver: bridge
services:
  mongodb:
    image: "bitnami/mongodb:4.0"
    ports:
      - "27128:27017"
    volumes:
      - "mongodb_data:/bitnami"
    networks:
      - peoplelogger
volumes:
  mongodb_data:
    driver: local
